### ISSUE TITLE
When preservation potion is equipped, time calculation is wrong.

### ISSUE THREAD

**Issue by Cinerar** [Boldy97/ironwood-scripts#21]
If i understand everything right, time need to be increased on preserved amount percentage while the time preservation potion is active.

**Comment by Boldy97** [comment]
It does, see below example.

Smithing with Cobalt Bars, no potion : 
![image](https://github.com/user-attachments/assets/c4c3daf4-7b73-42ab-8872-a2eeab717a26)

Same, but with Preservation Potions :
![image](https://github.com/user-attachments/assets/8e88aeb1-25e2-4d00-a0cb-299bbd5fe254)

I do think I know what might be happening for you.
When you unequip the potions, it's not properly processing the "empty potion slot" correctly
(it just ignores it, because it's nothing)
It's only fixed when you visit the equipment screen, that reads a complete equipment state, and correctly erases the crafting potion slot.

Could you confirm if that was your issue, @Cinerar ?

**Comment by Cinerar** [comment]
My mistake. Miscalculated.  (potion unequimpent error is another error, not bothering me much)
